# Fonts
font_family Iosevka
font_size 15.0
disable_ligatures always

# Cursor options
cursor none
cursor_shape beam
cursor_shape_unfocused beam
cursor_blink_interval 0

# Scrollback
scrollback_pager vim -Rn + -

# Terminal bell
enable_audio_bell no
visual_bell_duration 0.2 linear

# Window layout
confirm_os_window_close 0
resize_debounce_time 0.00 0.00
window_padding_width 8

# Color scheme
foreground #bbdddd
background #090919 

color16 #000008 # black
color0  #090919 # background
color8  #343351 # dark gray
color15 #708090 # light gray
color7  #bbccdd # white

color1  #cc3520 # red
color9  #ff6666 # light red

color2  #90cc00 # green
color10 #66ff66 # light green

color3  #c0b020 # yellow
color11 #ffff66 # light yellow

color4  #3366aa # blue
color12 #88bbff # light blue

color5  #860067 # magenta
color13 #ff66ff # light magenta

color6  #22aaaa # cyan
color14 #99ffff # light cyan

# Advanced
shell_integration enabled no-cursor
notify_on_cmd_finish unfocused 5 bell

# Mappable actions
map ctrl+shift+l combine | clear_terminal reset active | send_key  C C | send_text all clear; source ~/.bashrc | send_key enter
