# Fonts
font_family Terminess Nerd Font
font_size 14.0
disable_ligatures always

# Cursor options
cursor none
cursor_shape beam
cursor_shape_unfocused beam
cursor_blink_interval 0

# Scrollback
scrollback_pager vim -Rn + -

# Terminal bell
enable_audio_bell no
visual_bell_duration 0.2 linear

# Window layout
confirm_os_window_close 0
resize_debounce_time 0.00 0.00
window_padding_width 8

# Color scheme
foreground #ccbfaa
background #1c1510

color16 #130c03  # black
color0  #1a1310  # background
color8  #3f3335  # dark gray
color15 #9a8573  # light gray
color7  #ccbfaa  # white

color1 #883311 # red
color9 #bb6644 # red

color2 #668811 # green
color10 #98cc33 # light green

color3 #b59966 # yellow
color11 #ffdd99 # light yellow

color4 #595980 # blue
color12 #8888cc # light blue

color5 #665566 # magenta
color13 #998899 # magenta

color6 #669977 # cyan
color14 #aaccaa # light cyan

# Advanced
shell_integration enabled no-cursor
notify_on_cmd_finish unfocused 5 bell

# Mappable actions
map ctrl+shift+l combine | clear_terminal reset active | send_key  C C | send_text all clear; source ~/.bashrc | send_key enter
