-- Name:         vimper
-- Description:  Customized vim colorscheme
-- Author:       7sev7nsev7n7
-- License:      Same as Vim

-- This is Vim's default color scheme, improved.

vim.cmd.highlight('clear')
vim.g.colors_name = 'vimper'

local hi = function(name, val)
  -- Force links
  val.force = true

  -- Make sure that `cterm` attribute is not populated from `gui`
  val.cterm = val.cterm or {}

  -- Define global highlight
  vim.api.nvim_set_hl(0, name, val)
end

--stylua:ignorestart
--General
hi('Normal',                {ctermfg=7,ctermbg=0})
hi('Conceal',               {ctermfg=7,ctermbg=8})
hi('Cursor',                {cterm={reverse=true}})
hi('lCursor',               {})
hi('ErrorMsg',              {link='Error'})
hi('IncSearch',             {cterm={reverse=true}})
hi('ModeMsg',               {cterm={bold=true}})
hi('NonText',               {ctermfg=0})
hi('PmenuSbar',             {ctermbg=7})
hi('StatusLine',            {ctermbg=7,ctermfg=0})
hi('StatusLineNC',          {ctermbg=16,ctermfg=7,cterm={dim=true}})
hi('TabLineFill',           {cterm={reverse=true}})
hi('TabLineSel',            {cterm={bold=true}})
hi('TermCursor',            {cterm={reverse=true}})
hi('WinBar',                {cterm={bold=true}})
hi('WildMenu',              {ctermfg=0,ctermbg=11})
hi('FloatShadow',           {blend=80})
hi('FloatShadowThrough',    {blend=100})
hi('RedrawDebugNormal',     {reverse=true,cterm={reverse=true}})
hi('RedrawDebugClear',      {ctermbg=11})
hi('RedrawDebugComposed',   {ctermbg=10})
hi('RedrawDebugRecompose',  {ctermbg=12})
hi('Error',                 {ctermfg=0,ctermbg=9,cterm={bold=true}})
hi('Todo',                  {link='Title'})

hi('VertSplit',       {link="StatusLineNC"})
hi('WinSeparator',    {link='VertSplit'})
hi('WinBarNC',        {link='WinBar'})
hi('EndOfBuffer',     {link='NonText'})
hi('LineNrAbove',     {link='LineNr'})
hi('LineNrBelow',     {link='LineNr'})
hi('QuickFixLine',    {link='Search'})
hi('CursorLineSign',  {link='SignColumn'})
hi('CursorLineFold',  {link='FoldColumn'})
hi('CurSearch',       {ctermfg=0,ctermbg=7})
hi('PmenuKind',       {link='Pmenu'})
hi('PmenuKindSel',    {link='PmenuSel'})
hi('PmenuExtra',      {link='Pmenu'})
hi('PmenuExtraSel',   {link='PmenuSel'})
hi('Substitute',      {link='Search'})
hi('Whitespace',      {link='NonText'})
hi('MsgSeparator',    {link='StatusLine'})
hi('NormalFloat',     {link='Pmenu'})
hi('FloatBorder',     {link='WinSeparator'})
hi('FloatTitle',      {link='Title'})
hi('FloatFooter',     {link='Title'})

hi('String',          {ctermfg=15})
hi('Character',       {link='Constant'})
hi('Number',          {link='Constant'})
hi('Boolean',         {link='Constant'})
hi('Float',           {link='Number'})
hi('Function',        {link='Identifier'})
hi('Conditional',     {link='Statement'})
hi('Repeat',          {link='Statement'})
hi('Label',           {link='Statement'})
hi('Operator',        {link='Statement'})
hi('Keyword',         {link='Statement'})
hi('Exception',       {link='Statement'})
hi('Include',         {link='PreProc'})
hi('Define',          {link='PreProc'})
hi('Macro',           {link='PreProc'})
hi('PreCondit',       {link='PreProc'})
hi('StorageClass',    {link='Type'})
hi('Structure',       {link='Type'})
hi('Typedef',         {link='Type'})
hi('Tag',             {link='Special'})
hi('SpecialChar',     {link='Special'})
hi('Delimiter',       {link='Special'})
hi('SpecialComment',  {link='Special'})
hi('Debug',           {link='Special'})

hi('DiagnosticError',             {ctermfg=6})
hi('DiagnosticWarn',              {ctermfg=3})
hi('DiagnosticInfo',              {ctermfg=4})
hi('DiagnosticHint',              {ctermfg=7})
hi('DiagnosticOk',                {ctermfg=10})
hi('DiagnosticUnderlineError',    {cterm={underline=true}})
hi('DiagnosticUnderlineWarn',     {cterm={underline=true}})
hi('DiagnosticUnderlineInfo',     {cterm={underline=true}})
hi('DiagnosticUnderlineHint',     {cterm={underline=true}})
hi('DiagnosticUnderlineOk',       {cterm={underline=true}})
hi('DiagnosticVirtualTextError',  {link='DiagnosticError'})
hi('DiagnosticVirtualTextWarn',   {link='DiagnosticWarn'})
hi('DiagnosticVirtualTextInfo',   {link='DiagnosticInfo'})
hi('DiagnosticVirtualTextHint',   {link='DiagnosticHint'})
hi('DiagnosticVirtualTextOk',     {link='DiagnosticOk'})
hi('DiagnosticFloatingError',     {link='DiagnosticError'})
hi('DiagnosticFloatingWarn',      {link='DiagnosticWarn'})
hi('DiagnosticFloatingInfo',      {link='DiagnosticInfo'})
hi('DiagnosticFloatingHint',      {link='DiagnosticHint'})
hi('DiagnosticFloatingOk',        {link='DiagnosticOk'})
hi('DiagnosticSignError',         {link='DiagnosticError'})
hi('DiagnosticSignWarn',          {link='DiagnosticWarn'})
hi('DiagnosticSignInfo',          {link='DiagnosticInfo'})
hi('DiagnosticSignHint',          {link='DiagnosticHint'})
hi('DiagnosticSignOk',            {link='DiagnosticOk'})
hi('DiagnosticDeprecated',        {cterm={strikethrough=true}})
hi('DiagnosticUnnecessary',       {link='Comment'})
hi('LspInlayHint',                {link='NonText'})
hi('SnippetTabstop',              {link='Visual'})

-- Text
hi('@markup.raw',        {link='Comment'})
hi('@markup.link',       {link='Identifier'})
hi('@markup.heading',    {link='Title'})
hi('@markup.link.url',   {link='Underlined'})
hi('@markup.underline',  {link='Underlined'})
hi('@comment.todo',      {link='Todo'})

-- Miscs
hi('@comment',      {link='Comment'})
hi('@punctuation',  {link='Delimiter'})

-- Constants
hi('@constant',           {link='Constant'})
hi('@constant.builtin',   {link='Special'})
hi('@constant.macro',     {link='Define'})
hi('@keyword.directive',  {link='Define'})
hi('@string',             {link='String'})
hi('@string.escape',      {link='SpecialChar'})
hi('@string.special',     {link='SpecialChar'})
hi('@character',          {link='Character'})
hi('@character.special',  {link='SpecialChar'})
hi('@number',             {link='Number'})
hi('@boolean',            {link='Boolean'})
hi('@number.float',       {link='Float'})

-- Functions
hi('@function',                    {link='Function'})
hi('@function.builtin',            {link='Special'})
hi('@function.macro',              {link='Macro'})
hi('@function.method',             {link='Function'})
hi('@variable.parameter',          {link='Identifier'})
hi('@variable.parameter.builtin',  {link='Special'})
hi('@variable.member',             {link='Identifier'})
hi('@property',                    {link='Identifier'})
hi('@attribute',                   {link='Macro'})
hi('@attribute.builtin',           {link='Special'})
hi('@constructor',                 {link='Special'})

-- Keywords
hi('@keyword.conditional',  {link='Conditional'})
hi('@keyword.repeat',       {link='Repeat'})
hi('@keyword.type',         {link='Structure'})
hi('@label',                {link='Label'})
hi('@operator',             {link='Operator'})
hi('@keyword',              {link='Keyword'})
hi('@keyword.exception',    {link='Exception'})

hi('@variable',           {link='Identifier'})
hi('@type',               {link='Type'})
hi('@type.definition',    {link='Typedef'})
hi('@module',             {link='Identifier'})
hi('@keyword.import',     {link='Include'})
hi('@keyword.directive',  {link='PreProc'})
hi('@keyword.debug',      {link='Debug'})
hi('@tag',                {link='Tag'})
hi('@tag.builtin',        {link='Special'})

-- LSP semantic tokens
hi('@lsp.type.class',          {link='Structure'})
hi('@lsp.type.comment',        {link='Comment'})
hi('@lsp.type.decorator',      {link='Function'})
hi('@lsp.type.enum',           {link='Structure'})
hi('@lsp.type.enumMember',     {link='Constant'})
hi('@lsp.type.function',       {link='Function'})
hi('@lsp.type.interface',      {link='Structure'})
hi('@lsp.type.macro',          {link='Macro'})
hi('@lsp.type.method',         {link='Function'})
hi('@lsp.type.namespace',      {link='Structure'})
hi('@lsp.type.parameter',      {link='Identifier'})
hi('@lsp.type.property',       {link='Identifier'})
hi('@lsp.type.struct',         {link='Structure'})
hi('@lsp.type.type',           {link='Type'})
hi('@lsp.type.typeParameter',  {link='TypeDef'})
hi('@lsp.type.variable',       {link='Identifier'})

hi('ColorColumn',   {ctermbg=4})
hi('CursorColumn',  {link='CursorLine'})
hi('CursorLine',    {ctermbg=16,cterm={bold=true}})
hi('CursorLineNr',  {ctermfg=0,ctermbg=7})
hi('DiffText',      {ctermfg=11,ctermbg=0})
hi('DiffAdd',       {ctermbg=10,ctermfg=0})
hi('DiffChange',    {ctermfg=0,ctermbg=11,cterm={bold=true}})
hi('DiffDelete',    {ctermfg=9,ctermbg=9})
hi('Directory',     {ctermfg=5})
hi('Folded',        {ctermfg=8,ctermbg=0})
hi('FoldColumn',    {link='Folded'})
hi('LineNr',        {ctermfg=8})
hi('MatchParen',    {ctermfg=9,cterm={underdouble=true}})
hi('MoreMsg',       {ctermfg=12})
hi('Pmenu',         {ctermfg=0,ctermbg=13})
hi('PmenuSel',      {ctermfg=13,ctermbg=0})
hi('PmenuThumb',    {ctermfg=0})
hi('Question',      {ctermfg=14})
hi('Search',        {ctermfg=0,ctermbg=15})
hi('SignColumn',    {ctermbg=8})
hi('SpecialKey',    {cterm={underdouble=true}})
hi('SpellBad',      {ctermbg=4})
hi('SpellCap',      {ctermbg=9})
hi('SpellLocal',    {ctermbg=6})
hi('SpellRare',     {ctermbg=5})
hi('TabLine',       {cterm={underline=true}})
hi('Title',         {ctermfg=0,ctermbg=5,cterm={bold=true}})
hi('Visual',        {ctermfg=16,ctermbg=7})
hi('WarningMsg',    {ctermfg=4})
hi('Comment',       {ctermfg=8})
hi('Constant',      {ctermfg=6})
hi('Special',       {ctermfg=10})
hi('Identifier',    {ctermfg=3,cterm={bold=true}})
hi('Statement',     {ctermfg=2})
hi('PreProc',       {ctermfg=3})
hi('Type',          {ctermfg=1})
hi('Underlined',    {cterm={underline=true}})
hi('Ignore',        {ctermfg=0})
